// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh1bJnn1Oz412SlB8-Fair28mQJXiJKYs',
    appId: '1:754875278515:web:6aabfdf9045a648b5f7cc6',
    messagingSenderId: '754875278515',
    projectId: 'safe-8fe05',
    authDomain: 'safe-8fe05.firebaseapp.com',
    storageBucket: 'safe-8fe05.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf286YB1IGXgkEH5M3r1hdMWhVtTJaPZY',
    appId: '1:754875278515:android:73c5cffea59e871b5f7cc6',
    messagingSenderId: '754875278515',
    projectId: 'safe-8fe05',
    storageBucket: 'safe-8fe05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFHu5jkSYIABGqTErfO65okdtC3nzs_b8',
    appId: '1:754875278515:ios:3c0ec29a220483ae5f7cc6',
    messagingSenderId: '754875278515',
    projectId: 'safe-8fe05',
    storageBucket: 'safe-8fe05.firebasestorage.app',
    iosBundleId: 'com.example.smartWearable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFHu5jkSYIABGqTErfO65okdtC3nzs_b8',
    appId: '1:754875278515:ios:3c0ec29a220483ae5f7cc6',
    messagingSenderId: '754875278515',
    projectId: 'safe-8fe05',
    storageBucket: 'safe-8fe05.firebasestorage.app',
    iosBundleId: 'com.example.smartWearable',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh1bJnn1Oz412SlB8-Fair28mQJXiJKYs',
    appId: '1:754875278515:web:37d0ef0f1cb49fa85f7cc6',
    messagingSenderId: '754875278515',
    projectId: 'safe-8fe05',
    authDomain: 'safe-8fe05.firebaseapp.com',
    storageBucket: 'safe-8fe05.firebasestorage.app',
  );
}
